<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitac6358d883fa37741a7146bebe4d55a4
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Osms\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Osms\\' => 
        array (
            0 => __DIR__ . '/..' . '/ismaeltoe/osms/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitac6358d883fa37741a7146bebe4d55a4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitac6358d883fa37741a7146bebe4d55a4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitac6358d883fa37741a7146bebe4d55a4::$classMap;

        }, null, ClassLoader::class);
    }
}
